"""EMERGE script exporter.

Generates a text script that can be interpreted by EMERGE v2.x.
Format derived from EMerge User Manual 2.5.
"""
from __future__ import annotations
from typing import Any, Dict, List

from ..scene.em_objects import EMObject


def export_emerge_script(
    project_name: str,
    settings: Dict[str, Any],
    objects: List[EMObject],
    units: str = "mm",
) -> str:
    """Return the full EMERGE input script as a string."""
    lines: List[str] = []

    # ── Header ────────────────────────────────────────────────────────────────
    lines += [
        "# ─────────────────────────────────────────────────────────────────",
        f"# EMERGE script generated by EM 3D Modeler",
        f"# Project : {project_name}",
        "# ─────────────────────────────────────────────────────────────────",
        "",
        f'Project "{project_name}"',
        f'  Units = "{units}"',
        "EndProject",
        "",
    ]

    # ── Simulation parameters ─────────────────────────────────────────────────
    sim   = settings.get("simulation", {})
    fmin  = sim.get("Fmin_GHz",  0.0)
    fmax  = sim.get("Fmax_GHz",  10.0)
    fstep = sim.get("Fstep_GHz", 0.1)
    lines += [
        "Simulation",
        f"  Fmin  = {fmin}e9",
        f"  Fmax  = {fmax}e9",
        f"  Fstep = {fstep}e9",
        "EndSimulation",
        "",
    ]

    # ── Boundaries ────────────────────────────────────────────────────────────
    bounds = settings.get("boundaries", {})
    lines.append("Boundaries")
    for face, btype in bounds.items():
        lines.append(f'  {face} = "{btype}"')
    lines += ["EndBoundaries", ""]

    # ── Mesh ──────────────────────────────────────────────────────────────────
    mesh = settings.get("mesh", {})
    lines.append("Mesh")
    for k, v in mesh.items():
        lines.append(f"  {k} = {v}")
    lines += ["EndMesh", ""]

    # ── Ports ─────────────────────────────────────────────────────────────────
    for i, port in enumerate(settings.get("ports", []), start=1):
        ptype = port.get("type", "WaveguidePort")
        pname = port.get("name", f"Port{i}")
        lines += [
            f'Port "{pname}"',
            f'  Type  = "{ptype}"',
            f'  Index = {i}',
            f'  X     = {port.get("x", 0)}',
            f'  Y     = {port.get("y", 0)}',
            f'  Z     = {port.get("z", 0)}',
            "EndPort",
            "",
        ]

    # ── Materials ─────────────────────────────────────────────────────────────
    # Collect unique material names from objects
    used_materials: set = {obj.material for obj in objects}
    _MATERIAL_PARAMS = {
        "PEC":        ("PEC",         ""),
        "PMC":        ("PMC",         ""),
        "PML":        ("PML",         ""),
        "Air":        ("Dielectric",  "  Epsilon_r = 1.0\n  Mu_r = 1.0\n  SigmaE = 0.0"),
        "Dielectric": ("Dielectric",  "  Epsilon_r = 4.4\n  Mu_r = 1.0\n  SigmaE = 0.0"),
        "Custom":     ("Dielectric",  "  Epsilon_r = 1.0\n  Mu_r = 1.0\n  SigmaE = 0.0"),
    }
    for mat in sorted(used_materials):
        mtype, mparams = _MATERIAL_PARAMS.get(mat, ("Dielectric", "  Epsilon_r = 1.0"))
        lines += [f'Material "{mat}"', f'  Type = "{mtype}"']
        if mparams:
            lines += mparams.split("\n")
        lines += [f'EndMaterial', ""]

    # ── Geometry objects ──────────────────────────────────────────────────────
    lines.append("# ── Geometry ──────────────────────────────────────────────")
    for obj in objects:
        lines.append(obj.to_emerge_script())

    return "\n".join(lines)
