# ─────────────────────────────────────────────────────────────────
# EMERGE script generated by EM 3D Modeler
# Project : Untitled
# ─────────────────────────────────────────────────────────────────

Project "Untitled"
  Units = "mm"
EndProject

Simulation
  Fmin  = 0.0e9
  Fmax  = 10.0e9
  Fstep = 0.1e9
EndSimulation

Boundaries
  Xmin = "PML"
  Xmax = "PML"
  Ymin = "PML"
  Ymax = "PML"
  Zmin = "PML"
  Zmax = "PML"
EndBoundaries

Mesh
  MaxCellSize = 1.0
  MinCellSize = 0.05
  LinesPerWavelength = 10
EndMesh

Material "PEC"
  Type = "PEC"
EndMaterial

# ── Geometry ──────────────────────────────────────────────
Block "Box_1"
  Material = "PEC"
  XRange = [-20.0, 30.0]
  YRange = [-20.0, 0.0]
  ZRange = [0.0, 35.0]
EndBlock

Cylinder "Cylinder_1"
  Material = "PEC"
  Center = [10.0, -37.76395078288727, 20.0]
  Radius = 14.142135623730951
  Height = 35.52790156577454
  Axis = "Y"
EndCylinder
